[package]
name = "pong-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
nalgebra = "0.33.1"
pollster = "0.3.0"
wgpu = "22.1.0"
winit = "0.30.5"
